feat: [:sparkles:]腾讯云翻译引擎支持
YiiGuxing/TranslationPlugin pull request #766
Opened 2021-05-19 06:27 UTC by D-W-X

PR 特性：
- [x] 新引擎的支持

已知问题：
- 由于[接口原因](https://github.com/YiiGuxing/TranslationPlugin/issues/763#issuecomment-841372929)，不支持腾讯云地域设置，目前为上海；
- 错误信息使用腾讯云服务器返回的信息而没有本地化，当有使用问题时请去[链接](https://console.cloud.tencent.com/workorder/category?level1_id=536&level2_id=548&source=0&data_title=%E4%BA%91API&level3_id=549&queue=3232&scene_code=12739&step=2)开启工单。
- 腾讯云错误已知问题（可以继续向上一条的链接提工单）：
  - 只支持英文和中文，如果需要更多报错语言支持，请务必向腾讯方提工单。
  - 部分接口中文错误信息返回了英文。请将错误信息通过工单反馈给给腾讯云，需要他们后端优化。

**欢迎提供关于[翻译错误](https://cloud.tencent.com/document/product/551/30637)和[其他错误](https://cloud.tencent.com/document/product/551/15617#.E5.85.AC.E5.85.B1.E9.94.99.E8.AF.AF.E7.A0.81)（两个链接内容不同）国际化的PR！**

> 新语言需求工单模板：

> 您好，我这边因为业务需求，希望您方能考虑向 API 接口中的 Language 参数中加入对[语言名称]的支持，并返回对应语言下的错误信息。谢谢。

> 翻译不完整工单模板：

> 您好，我这边在使用腾讯云API时，当 Language 取值为 zh-CN 时，得到的错误信息却是英文，经排查发现是接口对 Language 参数的支持不完整，烦请贵方尽快修复，需要汉化的信息为：
> [翻译引擎的报错]

---

Feature:
- [x] new translate engine: tencent.

Konwn Issue:
- Beause of [the design of this plugin](https://github.com/YiiGuxing/TranslationPlugin/issues/763#issuecomment-841372929), it can only config api and key. Location for tencent translate engine is **not** supported till now. It's `Shanghai` by default.
- The translate error is **not** localized and used message from tencent translate server. If you have any issue, please be welcome to [create a ticket here for tencent](https://console.cloud.tencent.com/workorder/category?level1_id=536&level2_id=548&source=0&data_title=%E4%BA%91API&level3_id=549&queue=3232&scene_code=12739&step=2).
- Known issue for tencent translate engine:
  - English and Chinese is supported. If you prefer another lanaguage, do please create a ticket for tencent.

> Ticket Template for New Error Message Support:

> Hi there, I used tencent cloud API personally. When I invoke a method that is not success, I found I got error message not in my language when the 'Language' param is '[your language name]'. Would you like to add the translated error message in all interfaces? Thanks.

**PRs for the localized of [Translate Error Message](https://cloud.tencent.com/document/product/551/30637) and [Other Error Message](https://cloud.tencent.com/document/product/551/15617#.E5.85.AC.E5.85.B1.E9.94.99.E8.AF.AF.E7.A0.81) (two links with different content) are welcomed.**

2021-05-19 10:12 UTC, YiiGuxing commented
感谢您的PR，我会抽时间看一下的。

2021-05-20 09:56 UTC, YiiGuxing requested changes

2021-05-20 09:56 UTC, YiiGuxing commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/TencentTranslator.kt
> +    override val supportedTargetLanguages: List<Lang> = SUPPORTED_TARGET_LANGUAGES
我看了一下接口的文档，好像是不同的源语言支持的目标语言也是不同的，这个可能要想个办法适配一下。

2021-05-20 10:12 UTC, YiiGuxing commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/TencentTranslator.kt
> +    override val supportedTargetLanguages: List<Lang> = SUPPORTED_TARGET_LANGUAGES
这部分先不管吧，后面我来处理。

2021-05-20 10:14 UTC, d-w-x commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/TencentTranslator.kt
> +    override val supportedTargetLanguages: List<Lang> = SUPPORTED_TARGET_LANGUAGES
对，这个感觉难度高一些，两个集合搞不定的。

2021-05-20 10:16 UTC, d-w-x commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Languages.kt
> +    tencentErrorCode: String? = null
这里的话，其实更准确的来说是idea的本地语言（类似另一个pr的意思），我不清楚插件这里应该怎么获取？

2021-05-20 10:19 UTC, d-w-x commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Languages.kt
> +    tencentErrorCode: String? = null
这里的语音感觉有类似于#764的意思，等过两天我看看吧。

2021-05-20 11:27 UTC, YiiGuxing commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/TencentTranslator.kt
> +    override val supportedTargetLanguages: List<Lang> = SUPPORTED_TARGET_LANGUAGES
没事，你不用管，我已经有方案了的。

2021-05-20 11:41 UTC, YiiGuxing commented on src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Languages.kt
> +    tencentErrorCode: String? = null
就是参照百度有道的，自己做code和消息的对应表，然后在插件里做本地化。消息只要常用的几个就行。本地化的话，全写写中文就行，不用自己翻译，除非你精通英日朝三种语言。

2021-05-29 09:59 UTC, merged

2021-05-29 10:01 UTC, d-w-x commented
可能你需要顺便看看百度的error code形式也修改下？

2021-05-29 14:19 UTC, YiiGuxing commented
> 可能你需要顺便看看百度的error code形式也修改下？

百度的error code？这个不需要修改啊。

2021-05-29 14:23 UTC, d-w-x commented
> 百度的error code？这个不需要修改啊。

嗯嗯，你这个已经也修改了，之前特殊错误也是硬编码，我之前是照着百度错误写的。

可能合适的话得考虑怎么把不同api的错误合并下，感觉这个后期得归总这样子。

2021-05-29 14:34 UTC, YiiGuxing commented
> > 百度的error code？这个不需要修改啊。
> 
> 嗯嗯，你这个已经也修改了，之前特殊错误也是硬编码，我之前是照着百度错误写的。
> 
> 可能合适的话得考虑怎么把不同api的错误合并下，感觉这个后期得归总这样子。

嗯，是可以合并成两三类错误即可，现在的那些错误会出现的就没有几个。不过先不管了，翻译引擎后面得重写，到时候再考虑。